name: Trigger auto deployment for container-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-dev-AutoDeployTrigger-fed8517b-304c-4b07-8073-26ec4e72f0e1.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERDEV_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.CONTAINERDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERDEV_REGISTRY_PASSWORD }}
          containerAppName: container-dev
          resourceGroup: hive-frame
          imageToBuild: luizbrito6/container-dev:${{ github.sha }}
          

     

