name: Trigger auto deployment for fronk-isi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fronk-isi-AutoDeployTrigger-d9e2fb4a-18cf-4079-b53a-d85ac186a2ba.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FRONKISI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.FRONKISI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRONKISI_REGISTRY_PASSWORD }}
          containerAppName: fronk-isi
          resourceGroup: Projeto-ISI
          imageToBuild: luizbrito6/fronk-isi:${{ github.sha }}
          

     

